#Standard Languge you wat to use (see http://dev.bukkit.org/server-mods/antiad/ for valid values here)
Language: en
#Command sent to console when someone advertises
Command-Ad: tempban <player> <time> <reasonad>
#Command sent to console when someone spams
Command-Spam: kick <player> <reasonspam>
#The Amount of time they are banned for
Time: 5m
#The message players are given if not banned.
Spam_Message: DO NOT SPAM!
#The message players are given if not banned.
Ad_Message: DO NOT ADVERTISE!
#Broadcasts a notification that someone has been punished for advertising
Notification-Message: true
#Check if there are spam
Spam-Detection: true
#Says whether it will detect url's or not
URL-Detection: true
#check if there are any URLS ex. google.com
IP-Detection: true
#Check if all is Caps
Caps-Detection: true
#Checho for long spam 
Spam-Number-Letters-check: true
#Number of characters without a space that become spam
Spam-Number-Letters: 20
#Number of Capital Letters that become spam per word Eg More than 3 Letters Per Word Become Spam
Spam-Procent-Capital-Words: 80
#What commands the plugin listens to (private, me and so on.)
Detected-Commands:
- /msg
- /me
- /t
- /message
- /tell
#Warns admins when a player is spamming
SpamWarnAdmins: false
#Warns a admin when a player is advertising
AdWarnAdmins: true
#Number of times a player can spam/advertise before a action is taken we recommend it's set on 3.)
warnings: 3
#Should we replace text instead of removing it?
replaceText:
    advertisement: false
    caps: false
#Should we use the simple (alot can get through this pattern, we advice you to use the advanced one.
useSimpleWebPattern: false
